name: nightly

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            bin: yoc-linux-amd64
          - os: macos-13
            bin: yoc-macos-amd64
          - os: macos-14
            bin: yoc-macos-arm64
          - os: windows-latest
            bin: yoc-win64.exe
    steps:
      - uses: actions/checkout@v4

      - if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          install: |
            mingw-w64-x86_64-gcc
            make

      - name: build
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: make debug

      - name: build
        if: runner.os != 'Windows'
        run: make debug

      - name: package
        shell: bash
        run: |
          name="${{ matrix.bin }}"
          if [[ "${{ runner.os }}" == 'Windows' ]]; then
            mv yoc.exe "$name"
          else
            mv yoc "$name"
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.bin }}
          path: ${{ matrix.bin }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          path: binaries

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: nightly
          force_push_tag: true
          message: pre-release nightly

      - uses: softprops/action-gh-release@v2
        with:
          name: nightly
          tag_name: nightly
          files: binaries/**/*
          prerelease: true

      - run: rm -rf binaries
